allenai/rslearn

- rslearn/data_sources/__init__.py
- rslearn/train/lightning_module.py
1. Apply `restore_config` only for training, in this way, using the same configuration file, we won't apply `restore_config` when doing validation, test, and predict.
2. Add cache decorator to `data_source_from_config` to store the call results in memory.
> Some changes to speed up the prediction pipeline in reslearn_projects

- rslearn/train/lightning_module.py
Add condition to make sure that restoring weights is only triggered when it's a fresh fit (no previous checkpoints). 
Tested in rslearn_projects, when autoresume is True, only loading checkpoints, and when autoresume is False, only loading restored weights.
> Fix issue between restore_config and model checkpoints

- rslearn/data_sources/planet_basemap.py
This is needed for forest loss driver project because NICFI gives access to mosaics but not individual PSScene.
The Planet API Python SDK is used for the Planet data source but it only supports Data and Orders API, not Basemaps API. So we use `requests` and interact with the API directly here.
> [WIP] Add data source for Planet Labs basemap API.

- pyproject.toml
I think it makes sense to put a "v0.0.2" on pip before looking at PRs like #104 / #105 which have more substantial changes.
(e.g. it's possible that #104 will introduce subtle changes in how images are rendered and require retraining model)
> v0.0.2 release

- extra_requirements.txt
- rslearn/data_sources/climate_data_store.py
- tests/integration/data_sources/test_climate_data_store.py
For ERA5 data, I used the Climate Data Store (CDS) api: https://cds.climate.copernicus.eu/how-to-api. The ERA5-Land monthly averaged data from 1950 to present, specifically monthly averaged analysis data, link: https://cds.climate.copernicus.eu/datasets/reanalysis-era5-land-monthly-means?tab=download, has been added.
Since it's monthly data, I created one item per month, and its time_range covers the start and end date for a month. For a given STGeometry, it will generate all the year & month items within its time_range.
> Add ERA5 monthly data

- rslearn/main.py
- tests/integration/test_main.py
When we call the main cli through rslearn dataset materialize (or a similar command we are calling the main function directly so the mp context is not set from the if __name__ == "__main__":. We set it in the main function instead so it works for the entire rslearn main cli
> move context setting within main

- rslearn/tile_stores/default.py
- rslearn/utils/raster_format.py
- tests/unit/tile_stores/test_default.py
- tests/unit/utils/test_raster_format.py
This PR depends on #104 since it changes functionality in the new DefaultTileStore.
Currently we use LZW compression only.
This PR adds geotiff_options to GeotiffRasterFormat and DefaultTileStore so that arbitrary rasterio profile options can be overwritten. Then we can use the geotiff_options to enable ZSTD compression. In particular this seems to give a good tradeoff between speed and compression ratio:
```
raster_format = GeotiffRasterFormat(geotiff_options=dict(compress="zstd", zstd_level=1, predictor=2))
```
> Support using ZSTD compression in GeoTIFFs

- pyproject.toml
> Add py.typed to pyproject.toml.

- rslearn/data_sources/aws_landsat.py
- tests/integration/data_sources/test_aws_landsat.py
It was string so sorting would not be in the right order.
And then also it wasn't sorting the right list.
I added a test that fails without this fix.
> Fix bug in AWS Landsat data source where cloud cover is not used correctly

- rslearn/data_sources/aws_open_data.py
It was not using open_atomic so if manifest.txt was written partially by previous attempt, then the next time it would assume it was fully downloaded already and then it would create a partial rtree index and stuff.
> Fix bug in NAIP data source relating to writing manifest partially.

- rslearn/config/dataset.py
- tests/unit/config/test_dataset.py
These are for annotation / prediction layers to indicate which GeoJSON properties correspond to some notion of a class, or for non-image single-band GeoTIFFs to define what the different values in the band mean.
It could be useful in the future to do things like rasterize a vector layer to a corresponding raster layer; or we can move some similar definitions from model configuration file to dataset configuration file (e.g. make property_name/classes unnecessary in rslearn.train.tasks.classification.ClassificationTask). For now it will be used for ES Studio syncing.
> Add class_names/class_property_name to dataset config file

- extra_requirements.txt
- requirements.txt
- rslearn/train/lightning_module.py
- tests/integration/train/test_freeze_unfreeze.py
This fixes issue with using Python 3.12.8 (incompatibility between Lightning and jsonargparse).
I also bumped fsspec to 2025.2.0. Currently we pin the version because previously pip struggled to install the consistent latest version across fsspec/s3fs/gcsfs.
> Bump Lightning to 2.5.0.post0

- rslearn/main.py
This functionality has been superseded by rslearn_projects tooling for W&B. Users of rslearn can manage checkpointing/restoring in ways specific to the logging system and checkpointing location that they use.
Resolves #120.
> Remove wandb usage

- rslearn/utils/geometry.py
The main motivation was to increase the speed of rtree index creation in the gcp_public_data data source. It seems rasterio.warp.transform_geom takes 10+ ms even when the src/dst CRS are the same, so skipping the call saves a lot of time when we are doing many re-projections.
> Fast geometry to_projection when dst crs matches src crs.

- rslearn/tile_stores/default.py
- tests/unit/tile_stores/test_default.py
Fix issue where tmp files created by open_atomic cause error in DefaultTileStore.
The tmp files are created if there is an error during atomic write. The atomic write successfully prevents the actual filename from being written to, but the caller is expected to ignore these additional files that could get created.
Resolves #125.
> Fix issue where tmp files created by open_atomic cause error in DefaultTileStore

- rslearn/config/dataset.py
- rslearn/data_sources/raster_source.py
- rslearn/dataset/materialize.py
- rslearn/tile_stores/default.py
- rslearn/train/dataset.py
- rslearn/train/prediction_writer.py
- rslearn/utils/feature.py
- rslearn/utils/raster_format.py
- rslearn/utils/vector_format.py
- tests/fixtures/datasets/image_to_class.py
- tests/integration/data_sources/test_earthdata_srtm.py
- tests/integration/data_sources/test_local_files.py
- tests/integration/test_main.py
- tests/integration/utils/test_s3_dataset.py
- tests/unit/utils/test_raster_format.py
- tests/unit/utils/test_vector_format.py
Improve the API for RasterFormat and VectorFormat.
RasterFormat: the previous API accepts a projection and bounds when encoding, but only bounds when decoding. This commit changes it to also accept projection when decoding, and the RasterFormat is expected to re-project the data to the requested projection. Previously, the caller had to do extra work to ensure the bounds provided exactly matches the projection of the actual raster. Now, if the caller wants data in a different projection they can pass it rather than re-projecting themselves.
VectorFormat: the previous API accepts a projection when encoding (no bounds), and bounds when decoding (no projection). Encoding is changed to accept neither projection nor bounds: neither are necessary since the Features include a projection. …
> Improve the API for RasterFormat and VectorFormat.

- rslearn/data_sources/planet_basemap.py
- rslearn/dataset/manage.py
- rslearn/main.py
Some data sources have transient errors especially when making lots of API calls, e.g. we have had issues with the PlanetBasemap and PlanetaryComputer data sources. So it can be useful to have a general-purpose retry option rather than implementing retry loop inside every problematic data source.
> Support retry loop for prepare/ingest/materialize.

- .github/workflows/data-source-integration-test.yml
- rslearn/data_sources/copernicus.py
- tests/integration/data_sources/test_copernicus.py
This retrieves rasters from the Copernicus API. It is currently tested with Sentinel-2 only, and there is a subclass that provides support for Sentinel-2 harmonization, although harmonization may not be needed since ESA has re-processed most if not all of the old scenes.
Resolves #15.
> Add Copernicus data source.

- rslearn/data_sources/planetary_computer.py
Reduce the STAC calls made by PlanetaryComputer during ingestion/materialization.
During direct materialization in particular, we previously would make 3 STAC calls to get STAC item by ID: once in get_raster_bands, once in get_raster_bounds, and once in read_raster.
Now we expose a cache_dir option so we save the asset URLs during preparing, so we don't need any of these calls. Although the asset URLs are now saved with the item, the cache_dir is still needed because we don't currently have access to the item objects when materializing with a TileStore interface.
This speeds up direct materialization substantially since previously the STAC API calls were a bottleneck.
> Reduce the STAC calls made by PlanetaryComputer during ingestion/materialization

- rslearn/data_sources/aws_landsat.py
- rslearn/data_sources/utils.py
- tests/unit/data_sources/test_match_candidate_items_to_window.py
Previously we would iterate over items, and if an item didn't add coverage to the current mosaic then we would skip it. Now we push it down to the next mosaic and so on to see if it can be added to any of them.
Resolves #159.
> Improve mosaic creation by adding items to ladder of mosaics.

- rslearn/train/dataset.py
Previously if there are multiple tags, then a window would be added as a training example for each tag that it matches. This means there would be duplicates, and also it doesn't match the intended behavior where the tags are additive constraints (i.e. the overall op should be logical and of all the specified tags).
This commit fixes the bug.
> Fix bug with multiple tags in a SplitConfig.

- rslearn/data_sources/climate_data_store.py
- tests/integration/data_sources/test_climate_data_store.py
Previously if the windows have global coverage, the data source would make a request for data across the world, but this request would fail for some reason.
Additionally, it is like OpenStreetMap data source where the items are dependent on the requested windows rather than independent.
This changes ERA5 to represent the underlying data as fixed 10x10 degree items (even though the API supports arbitrary geometry requests) and matches those to windows. The size of an item can be configured if desired but the point is there is a fixed grid. Temporally it is still gridded by calendar month.
> Improve ERA5 data source to work with larger-scale window collections.

- rslearn/train/dataset.py
- tests/integration/train/test_dataset.py
https://github.com/allenai/rslearn/pull/156 introduced a bug where, if a window doesn't have a tag that's set in the model configuration file, then it will cause an error (KeyError). This PR fixes that bug while also adding a test.
> Fix bug when tags aren't specified on the window

- rslearn/data_sources/aws_landsat.py
Currently it is slow because (a) it has to read the WRS2 polygons from cache dir on every get_items call, and (b) it doesn't use grid index over the polygons.
I also updated it to use _stac.json instead of _MTL.json since the former contains a more accurate geometry of the image (I think the latter is just the bounding box but some portions may be missing).
> Speed up aws-landsat preparing by using grid index and caching it.

- rslearn/train/lightning_module.py
- rslearn/train/tasks/detection.py
Speed up detection metric speed to reduce validation duration.
We speed up in two ways:
- Add enable_precision_recall option so that by default we support only logging F1 score. Each one does redundant computation so far and metric can only return one scalar with lightning, so disabling precision/recall logging makes it much faster.
- Currently the speed gets slower and slower. I don't know the exact reason, but the part that gets slower is logging the metric, even though we pass on_epoch=True. Moving to epoch end and manually resetting the metric avoids this slowdown. UPDATE: I reverted this because it was causing errors relating to distributed sync. It seems only mAP metric gets slower, our implementation works fine since we don't store list that gets longer and longer, disabling mAP …
> Speed up detection metric speed to reduce how long validation step takes

- rslearn/main.py
- rslearn/train/data_module.py
Previously, when setting a sampler in SplitConfig with multi-GPU training, the sampler would just get overwritten by pytorch Lightning since it would configure a DistributedSampler. When using rslearn_projects, it happens even with single-GPU training since we currently always enable ddp to set find_unused_parameters.
This leads to confusing bugs where you expect it to use e.g. random weighted sampling but the option is effectively ignored since Lightning configures a different sampler.
Now the DistributedSampler replacement functionality is disabled, and we instead configure the sampler appropriately in the data module even when sampler factory is not set.
> Fix issues using custom samplers with multi-GPU training

- rslearn/main.py
- rslearn/models/multitask.py
- rslearn/train/callbacks/peft.py
- rslearn/train/data_module.py
- rslearn/train/dataset.py
- rslearn/train/lightning_module.py
- rslearn/train/tasks/multi_task.py
Finetuning on multiple datasets in memory at once.
Currently only allows one task per dataset - this is the highest priority next fix, since some datasets (ex: v2_pastis) have ambiguous task names like detect or classify that collide with other datasets.
Occasionally there are NCCL hangs at the end of validation loops, this has been hard to reproduce/debug in isolation so unclear if this is due to multi-dataset training or a larger issue.
Also adds support for [ALPA](https://arxiv.org/html/2503.11335v2), but this isn't recommended as the performance gains during backward are quite small. Unclear why this is, maybe something to do with switching off gradients at such a finegrained parameter level?
> Finetuning on concatenated datasets

- docs/examples/WindowsFromGeojson.md
- rslearn/dataset/dataset.py
- rslearn/dataset/index.py
- rslearn/dataset/window.py
- rslearn/main.py
- rslearn/train/dataset.py
- tests/integration/train/test_dataset.py
- tests/unit/dataset/test_index.py
Resolves #161.
Currently, loading windows can take several minutes or even hours, depending on the number of windows and where the dataset is stored. This is especially annoying when we need to wait for the loading to complete before the model starts training.
This PR adds a DatasetIndex. The index is stored in a single file/object, so it can be retrieved relatively quickly; it isn't compressed, so we read about the same number of bytes, but reading a single file is much faster than reading hundreds of thousands of files. The index enumerates the windows and their metadata (metadata.json), along with the layer datas (items.json) and which layers are "completed".
A new `rslearn dataset build_index` command is added, and we check if the index exists when calling Dataset.load_windows. If it …
> Supporting building and saving an index over windows to speed up window loading

- pyproject.toml
- tests/unit/models/test_clip.py
- tests/unit/models/test_croma.py
- tests/unit/models/test_terramind.py
Model deletion fails nondeterministically because we have parallel test workers. For example, TerraMind and CLIP test both use HuggingFace so the deletion will conflict.
This PR changes it to use temporary directory instead by monkeypatching the relevant attributes. I updated pyproject.toml to direct pytest to only keep temp dirs from failing tests as well, since otherwise they would be retained which would defeat the point of this (to delete checkpoints immediately after the test is done in github action workers).
> Model deletion fails nondeterministically because we have parallel test workers

- rslearn/models/multitask.py
Checkpoint restoring can be configured via the `restore_config: RestoreConfig` argument to `RslearnLightningModule`. See for example https://github.com/allenai/rslearn_projects/blob/18e1ea18c62f60ed5bad231a61a5c8ac92d4c126/data/satlas/solar_farm/config.yaml#L31
So I think the `checkpoint_path` argument to `MultiTaskModel` is not needed. This PR removes that argument.
Let me know if there are actually some cases that the existing code in RslearnLightningModule cannot handle. In that case I still think it would be best to expand the options for RestoreConfig rather than having checkpoint restore code in each model implementation.
> Remove redundant checkpoint restoring code from MultiTaskModel

- rslearn/models/multitask.py
- rslearn/train/lightning_module.py
- rslearn/train/tasks/classification.py
- rslearn/train/tasks/regression.py
- rslearn/train/tasks/segmentation.py
- tests/conftest.py
- tests/fixtures/datasets/image_to_class.py
- tests/integration/train/test_freeze_unfreeze.py
- tests/integration/train/test_prediction_writer.py
Fix bug in `model predict` due to combination of returned losses being None and MultiTaskModel trying to apply task_weights.
I updated the ClassificationTask, SegmentationTask, and RegressionTask to return empty loss dict instead of loss dict with None loss entry.
I also moved the task_weights from MultiTaskModel to RslearnLightningModule so it can be applied for different kinds of models and also for individual losses within a task instead of just across tasks (e.g. object detection returns multiple losses that can be weighted separately). This will also avoid error in case there are custom Tasks that still return None in the loss dict.
I added integration test for this that fails without the changes. I also fixed a bug with ClassificationTask.process_outputs when read_class_id is set, …
> Fix bug in model predict

- docs/DatasetConfig.md
- rslearn/config/__init__.py
- rslearn/config/dataset.py
- rslearn/data_sources/utils.py
- rslearn/dataset/materialize.py
- tests/unit/dataset/test_materialize.py
**Summary**
This PR adds functionality to create mean and median composites.
**Changes**
- Query Config spatial mode now includes `COMPOSITE` -> creates single group for evrey window containing all items in time range.
- RasterLayer Config now includes `compositing_method` option, allowing to specify `FIRST_VALID | MEAN | MEDIAN`.
**Discussion Points**
- Mean compositing: Currently quite memory inefficient: Loads all items windows of the time-period into memory. We might want to think about doing more of a running mean / running-sum approach to reduce memory requirements. Did a short benchmark and running-mean was on average 45% slower however reduced memory significantly depending on the number of items.
- Max_matches: Compositing is currently not using `max_matches` as I believe only a …
> Adding Temporal Compositing Options

- rslearn/train/dataset.py
If load_all_layers is set, require all the layers to be materialized.
Previously, if batch_size > 1 and some windows have only a subset of the configured layers with load_all_layers=true, we would end up with batches of examples where each example has time series of a different length, and the models won't work.
In the future, we may want this to be a separate option, so you can stack data from whatever layers are available, but still use the windows with only a subset of the layers materialized. Currently, though, all the existing models require consistent batches so it makes more sense to just connect load_all_layers with needing all the configured layers to be present.
> If load_all_layers is set, require all the layers to be materialized

- .github/workflows/build-test.yml
- docs/Development.md
- tests/integration/conftest.py
The `test_bucket` and `test_prefix` fixtures seem to just set some defaults for environment variables. It seems better to let the tests that depend on them fail if the environment variables are not set, rather than set defaults that would only work for people with access to that specific bucket.
Resolves #260.
> Remove unnecessary test fixtures

- pyproject.toml
- rslearn/arg_parser.py
- rslearn/dataset/dataset.py
- rslearn/template_params.py
- tests/unit/dataset/test_dataset.py
- tests/unit/test_arg_parser.py
- uv.lock
In the same vein as #278 + #283, this changeset allows
template variables of the format `${TEMPLATE_VAR}` into
dataset config.jsons, which will be overwritten with
injectable env vars at startup. It leverages the same logic
that was used in model.yaml's argparser, but applied
during Dataset construction.
The changes facilitate esrun's need to to coordinate the writing
of label layers before fine tuning and targeting of prediction
output layers during inference into a discoverable location.
> Allows template parameters in dataset config.json

- rslearn/models/resize_features.py
- tests/unit/models/test_resize_features.py
This transform resizes multiple feature maps to a fixed size. It is helpful for model architectures that require input to be resized to a certain shape, so we can resize the output features back to a shape that is power of 2 off from the input size.
> Add ResizeFeatures transform.
